### ISSUE TITLE
npx react-native-rename breaks the app

### ISSUE THREAD

**Issue by belizar** [orYoffe/create-react-native-web-app#51] opened 2019-09-04 14:43 UTC
Look at the image,
![image](https://user-images.githubusercontent.com/37871475/64265412-39a0b700-cf09-11e9-8549-c5b5f8086f05.png)

**Comment by orYoffe** [comment] 2019-11-20 19:51
this is because of the renaming library.. if you'd like to work on it it's a good first issue. thanks for sharing :)

I hope it didn't stop you from coding.
you can install the dependencies yourself by doing `npm i` or `yarn` inside the project folder and start coding away :)

**Comment by giliyoffe** [comment] 2020-02-04 22:23
@belizar can you still reproduce this issue?
I can not reproduce it.
@orYoffe did you fix it?
thanks

**Comment by orYoffe** [comment] 2020-02-06 21:43
closing issue since nothing happened with this plus doesn't seem like i can reproduce it

**Closed by orYoffe** 2020-02-06 21:43 UTC
Labels: good first issue
