### ISSUE TITLE
Path myApp\android\app\src\main\java\com\myapp empty on windows

### ISSUE THREAD

**Issue by luizcarlospedrosogomes** [orYoffe/create-react-native-web-app#43] opened 2019-04-25 10:36 UTC
![image](https://user-images.githubusercontent.com/9791364/56729867-a8d0f800-672c-11e9-8811-2ee4746aeb9b.png)

OS; windows 10 x 64
react-native-cli: 2.0.1
react-native: 0.55.4
emulador: android studio

**Comment by orYoffe** [comment] 2019-04-26 13:41
@luizcarlospedrosogomes could you please write the steps to reproduce?
did you run `npm start` and `npm run android`?

**Comment by luizcarlospedrosogomes** [comment] 2019-04-26 23:34
@orYoffe npm run android

**Comment by luizcarlospedrosogomes** [comment] 2019-04-27 15:58
copy files of C:\Users\User\AppData\Roaming\npm\node_modules\create-react-native-web-app\template\android\app\src\main\java\com\creaternwapp

edit for: package com.appFake; and correct for your app


![image](https://user-images.githubusercontent.com/9791364/56852027-03648280-68ec-11e9-98d4-ce8e47ca91b1.png)

but not reload affter save src/App.js

**Comment by canyavall** [comment] 2019-04-29 06:31
I had same issue, I had to copy both files from the template (windows 10)

**Comment by luizcarlospedrosogomes** [comment] 2019-05-01 19:27
this bug for windows 10

**Comment by DrAndri** [comment] 2019-08-06 00:03
Had this issue as well. When creating the app there were a bunch of `The system cannot find the path specified` errors without any further info. 

running `react-native upgrade` after running `create-react-native-web-app` generated the missing files and fixed the problem for me

**Comment by orYoffe** [comment] 2019-11-20 19:52
would love some help with this as it's not happening to me. maybe one of you could find a solution and produce a PR?

**Comment by orYoffe** [comment] 2020-02-06 21:45
closing issue since nothing happened with this plus doesn't seem like i can reproduce it

**Closed by orYoffe** 2020-02-06 21:45 UTC
Labels: good first issue
